TARGET = m-vba

CROSS_COMPILE =

CC = $(CROSS_COMPILE)arm-linux-gcc

OBJS = gba.o memory.o sound.o system.o sound_output.o core.o input.o \
	font_drawing.o menu.o scaler.o video_blit.o

VPATH = ./src

CFLAGS = -Iinclude -march=armv5te -mtune=arm926ej-s -O2  -fno-common -Wall -std=gnu++11 \
	-DLSB_FIRST -DWANT_16BPP -DFRONTEND_SUPPORTS_RGB565 -DNDEBUG -DWANT_STEREO_SOUND  \
	`sdl-config --cflags` -funroll-loops -fno-strict-aliasing		\
	-fomit-frame-pointer

ASFLAGS = -march=armv5te -mtune=arm926ej-s

LDFLAGS = -march=armv5te -mtune=arm926ej-s -static -DVIRTUAL_SURFACE \
	-lc -lgcc -lm `sdl-config --libs` -lasound -lz -Wl,--as-needed -Wl,--gc-sections

#PGO = YES
PGO = APPLY

ifeq ($(PGO), YES)
CFLAGS += -fprofile-generate=./profile
LDFLAGS += -lgcov -fprofile-generate=./profile
TARGET = m-vba_pm
else ifeq ($(PGO), APPLY)
CFLAGS += -fprofile-use=./profile -fbranch-probabilities
endif

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDFLAGS)
	@echo Done!!!

%.o: %.S
	$(CC) $(ASFLAGS) -c $< -o $@

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.o $(TARGET)