TARGET = m-vba

CROSS_COMPILE = arm-linux-

CC = $(CROSS_COMPILE)gcc

OBJS = gba.o memory.o sound.o system.o sound_output.o core.o input.o \
	font_drawing.o menu.o scaler.o video_blit.o

VPATH = ./src

CFLAGS = -Iinclude -march=armv5te -mtune=arm926ej-s -O2  -fno-common -Wall -std=gnu++11 \
	-DLSB_FIRST -DWANT_16BPP -DFRONTEND_SUPPORTS_RGB565 -DNDEBUG -DWANT_STEREO_SOUND  \
	-DVIRTUAL_SURFACE `sdl-config --cflags`

ASFLAGS = -march=armv5te -mtune=arm926ej-s

LDFLAGS = -march=armv5te -mtune=arm926ej-s  \
	  -lc -lgcc -lm -lSDL -lasound -lz -Wl,--as-needed -Wl,--gc-sections  

#PGO = YES
PGO = APPLY

ifeq ($(PGO), YES)
CFLAGS += -fprofile-generate=./profile
LDFLAGS += -lgcov -fprofile-generate=./profile
TARGET = m-vba_pm
else ifeq ($(PGO), APPLY)
CFLAGS += -fprofile-use=./ -fbranch-probabilities
endif

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) $(OBJS) -o $@
	@echo Done!!!

%.o: %.S
	$(CC) $(ASFLAGS) -c $< -o $@

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.o $(TARGET)